<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title><?php getTitle();?></title>
	<link rel="stylesheet" type="text/css" href="<?php echo $css?>bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="<?php echo $css?>font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="layout/main.css">
	<link href="layout/main.css?<?=filemtime("layout/main.css")?>" rel="stylesheet" type="text/css" />
</head>
<body>
